### ISSUE TITLE
试用了下，反应速度非常快，请问一下您是用的plus版吗？

### ISSUE THREAD

**Issue by Quantatirsk** [youngle316/chatgpt#18]
目前官方API好像还不支持上下文记忆吧

**Comment by youngle316** [comment]
不是plus版本。就是使用的该项目[chatgpt-api](https://github.com/transitive-bullshit/chatgpt-api)，今天早上更新到最新的 `gpt-3.5-turbo-0301`了，比`text-davinci-003`模型确实快很多

**Comment by youngle316** [comment]
> 目前官方API好像还不支持上下文记忆吧

支持的，项目中现在已经添加了
